apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wordpress-tls
  namespace: default
spec:
  secretName: wordpress-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: hostname
  dnsNames:
  - hostname